/* ==========================================================================
   The rules of chess, in the browser.

   GENERATED from server.ts — do not edit this file by hand. It is the same
   code the server runs, with the TypeScript stripped and nothing else changed:
   `scripts/build-chess-rules.sh` regenerates it, and scripts/test-chess.ts
   fails if it has drifted.

   Why there are two copies at all. The pit's chess table can be played for
   sahurs, so the rules that decide a pot have to be the server's, and the pit
   client is handed a list of legal moves rather than the means to work them
   out. THIS copy is for the game against the computer in games/tung/chess.html,
   which runs entirely in the browser, stakes nothing and asks the backend for
   nothing at all. If the two ever disagreed the server would be right by
   definition — which is exactly why this one is generated rather than written.

   The generator is verified where the original lives: perft against the
   published node counts for six standard positions, about sixteen million of
   them.
   ========================================================================== */
var __CR = (() => {
  var __defProp = Object.defineProperty;
  var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
  var __getOwnPropNames = Object.getOwnPropertyNames;
  var __hasOwnProp = Object.prototype.hasOwnProperty;
  var __export = (target, all) => {
    for (var name in all)
      __defProp(target, name, { get: all[name], enumerable: true });
  };
  var __copyProps = (to, from, except, desc) => {
    if (from && typeof from === "object" || typeof from === "function") {
      for (let key of __getOwnPropNames(from))
        if (!__hasOwnProp.call(to, key) && key !== except)
          __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
    }
    return to;
  };
  var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
  var chess_src_exports = {};
  __export(chess_src_exports, {
    CHESS_START: () => CHESS_START,
    chessApply: () => chessApply,
    chessEnd: () => chessEnd,
    chessFen: () => chessFen,
    chessFromUci: () => chessFromUci,
    chessInCheck: () => chessInCheck,
    chessKey: () => chessKey,
    chessMoves: () => chessMoves,
    chessParse: () => chessParse,
    chessSan: () => chessSan,
    chessSq: () => chessSq,
    chessUci: () => chessUci
  });
  const P = 1;
  const N = 2;
  const B = 3;
  const R = 4;
  const Q = 5;
  const K = 6;
  const LETTER = ".PNBRQK";
  const FILE = (i) => i & 7;
  const RANK = (i) => i >> 3;
  function chessParse(fen) {
    const parts = String(fen).trim().split(/\s+/);
    if (parts.length < 4) return null;
    const b = new Int8Array(64);
    const rows = parts[0].split("/");
    if (rows.length !== 8) return null;
    for (let r = 0; r < 8; r++) {
      let f = 0;
      for (const ch of rows[r]) {
        if (ch >= "1" && ch <= "8") {
          f += Number(ch);
          continue;
        }
        const up = ch.toUpperCase();
        const k = LETTER.indexOf(up);
        if (k <= 0 || f > 7) return null;
        b[(7 - r) * 8 + f] = ch === up ? k : -k;
        f++;
      }
      if (f !== 8) return null;
    }
    const w = parts[1] === "w";
    let cs = 0;
    if (parts[2] !== "-") {
      for (const ch of parts[2]) {
        const k = "KQkq".indexOf(ch);
        if (k < 0) return null;
        cs |= 1 << k;
      }
    }
    let ep = -1;
    if (parts[3] !== "-") {
      const f = parts[3].charCodeAt(0) - 97, r = Number(parts[3][1]) - 1;
      if (f < 0 || f > 7 || r < 0 || r > 7) return null;
      ep = r * 8 + f;
    }
    const half = parts.length > 4 ? Number(parts[4]) : 0;
    const full = parts.length > 5 ? Number(parts[5]) : 1;
    if (!Number.isFinite(half) || !Number.isFinite(full)) return null;
    return { b, w, cs, ep, half: Math.max(0, half | 0), full: Math.max(1, full | 0) };
  }
  function chessFen(p) {
    const rows = [];
    for (let r = 7; r >= 0; r--) {
      let s = "", gap = 0;
      for (let f = 0; f < 8; f++) {
        const v = p.b[r * 8 + f];
        if (!v) {
          gap++;
          continue;
        }
        if (gap) {
          s += gap;
          gap = 0;
        }
        const ch = LETTER[Math.abs(v)];
        s += v > 0 ? ch : ch.toLowerCase();
      }
      if (gap) s += gap;
      rows.push(s);
    }
    let cs = "";
    for (let i = 0; i < 4; i++) if (p.cs & 1 << i) cs += "KQkq"[i];
    const ep = p.ep < 0 ? "-" : String.fromCharCode(97 + FILE(p.ep)) + (RANK(p.ep) + 1);
    return `${rows.join("/")} ${p.w ? "w" : "b"} ${cs || "-"} ${ep} ${p.half} ${p.full}`;
  }
  const CHESS_START = "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1";
  const KN = [17, 15, 10, 6, -17, -15, -10, -6];
  const KD = [8, -8, 1, -1, 9, 7, -9, -7];
  const BD = [9, 7, -9, -7];
  const RD = [8, -8, 1, -1];
  function step(from, d) {
    const to = from + d;
    if (to < 0 || to > 63) return -1;
    const df = Math.abs(FILE(to) - FILE(from));
    if (df > 2) return -1;
    return to;
  }
  function chessAttacked(p, sq, byWhite) {
    const sign = byWhite ? 1 : -1;
    for (const d of byWhite ? [-9, -7] : [9, 7]) {
      const s = step(sq, d);
      if (s >= 0 && p.b[s] === sign * P) return true;
    }
    for (const d of KN) {
      const s = step(sq, d);
      if (s >= 0 && p.b[s] === sign * N) return true;
    }
    for (const d of KD) {
      const s = step(sq, d);
      if (s >= 0 && p.b[s] === sign * K) return true;
    }
    for (const d of BD) {
      let s = step(sq, d);
      while (s >= 0) {
        const v = p.b[s];
        if (v) {
          if (v === sign * B || v === sign * Q) return true;
          break;
        }
        s = step(s, d);
      }
    }
    for (const d of RD) {
      let s = step(sq, d);
      while (s >= 0) {
        const v = p.b[s];
        if (v) {
          if (v === sign * R || v === sign * Q) return true;
          break;
        }
        s = step(s, d);
      }
    }
    return false;
  }
  function kingOf(p, white) {
    const want = white ? K : -K;
    for (let i = 0; i < 64; i++) if (p.b[i] === want) return i;
    return -1;
  }
  function chessInCheck(p, white) {
    const k = kingOf(p, white);
    return k >= 0 && chessAttacked(p, k, !white);
  }
  function pushPromos(out, from, to) {
    for (const promo of [Q, R, B, N]) out.push({ from, to, promo });
  }
  function pseudo(p) {
    const out = [];
    const me = p.w ? 1 : -1;
    const last = p.w ? 7 : 0;
    for (let i = 0; i < 64; i++) {
      const v = p.b[i];
      if (!v || Math.sign(v) !== me) continue;
      const t = Math.abs(v);
      if (t === P) {
        const fwd = p.w ? 8 : -8;
        const one = i + fwd;
        if (one >= 0 && one < 64 && !p.b[one]) {
          if (RANK(one) === last) pushPromos(out, i, one);
          else {
            out.push({ from: i, to: one, promo: 0 });
            const home2 = p.w ? 1 : 6;
            const two = i + fwd * 2;
            if (RANK(i) === home2 && !p.b[two]) out.push({ from: i, to: two, promo: 0 });
          }
        }
        for (const d of p.w ? [7, 9] : [-7, -9]) {
          const s = step(i, d);
          if (s < 0) continue;
          const tv = p.b[s];
          if (tv && Math.sign(tv) !== me || s === p.ep) {
            if (RANK(s) === last) pushPromos(out, i, s);
            else out.push({ from: i, to: s, promo: 0 });
          }
        }
      } else if (t === N || t === K) {
        for (const d of t === N ? KN : KD) {
          const s = step(i, d);
          if (s < 0) continue;
          const tv = p.b[s];
          if (!tv || Math.sign(tv) !== me) out.push({ from: i, to: s, promo: 0 });
        }
      } else {
        const dirs = t === B ? BD : t === R ? RD : KD;
        for (const d of dirs) {
          let s = step(i, d);
          while (s >= 0) {
            const tv = p.b[s];
            if (!tv) out.push({ from: i, to: s, promo: 0 });
            else {
              if (Math.sign(tv) !== me) out.push({ from: i, to: s, promo: 0 });
              break;
            }
            s = step(s, d);
          }
        }
      }
    }
    const home = p.w ? 4 : 60;
    if (p.b[home] === me * K) {
      const kSide = p.w ? 1 : 4, qSide = p.w ? 2 : 8;
      const rk = p.w ? 7 : 63, rq = p.w ? 0 : 56;
      if (p.cs & kSide && p.b[rk] === me * R && !p.b[home + 1] && !p.b[home + 2]) {
        if (!chessAttacked(p, home, !p.w) && !chessAttacked(p, home + 1, !p.w) && !chessAttacked(p, home + 2, !p.w)) out.push({ from: home, to: home + 2, promo: 0 });
      }
      if (p.cs & qSide && p.b[rq] === me * R && !p.b[home - 1] && !p.b[home - 2] && !p.b[home - 3]) {
        if (!chessAttacked(p, home, !p.w) && !chessAttacked(p, home - 1, !p.w) && !chessAttacked(p, home - 2, !p.w)) out.push({ from: home, to: home - 2, promo: 0 });
      }
    }
    return out;
  }
  function chessApply(p, m) {
    const b = Int8Array.from(p.b);
    const me = p.w ? 1 : -1;
    const piece = b[m.from];
    const t = Math.abs(piece);
    const captured = b[m.to];
    b[m.to] = piece;
    b[m.from] = 0;
    if (t === P && m.to === p.ep && !captured) b[m.to - (p.w ? 8 : -8)] = 0;
    if (t === P && m.promo) b[m.to] = me * m.promo;
    if (t === K && Math.abs(m.to - m.from) === 2) {
      const mid = m.from + m.to >> 1;
      const rookFrom = m.to > m.from ? m.from + 3 : m.from - 4;
      b[mid] = b[rookFrom];
      b[rookFrom] = 0;
    }
    let cs = p.cs;
    if (t === K) cs &= p.w ? ~3 : ~12;
    for (const [sq, bit] of [[0, 2], [7, 1], [56, 8], [63, 4]]) {
      if (m.from === sq || m.to === sq) cs &= ~bit;
    }
    const ep = t === P && Math.abs(m.to - m.from) === 16 ? m.from + m.to >> 1 : -1;
    return {
      b,
      w: !p.w,
      cs,
      ep,
      half: t === P || captured ? 0 : p.half + 1,
      full: p.full + (p.w ? 0 : 1)
    };
  }
  function chessMoves(p) {
    const out = [];
    for (const m of pseudo(p)) {
      const n = chessApply(p, m);
      if (!chessInCheck(n, p.w)) out.push(m);
    }
    return out;
  }
  function chessSq(i) {
    return String.fromCharCode(97 + FILE(i)) + (RANK(i) + 1);
  }
  function chessUci(m) {
    return chessSq(m.from) + chessSq(m.to) + (m.promo ? LETTER[m.promo].toLowerCase() : "");
  }
  function chessFromUci(s) {
    const t = String(s).trim().toLowerCase();
    if (!/^[a-h][1-8][a-h][1-8][qrbn]?$/.test(t)) return null;
    const sq = (a, b) => (Number(b) - 1) * 8 + (a.charCodeAt(0) - 97);
    return {
      from: sq(t[0], t[1]),
      to: sq(t[2], t[3]),
      promo: t[4] ? LETTER.indexOf(t[4].toUpperCase()) : 0
    };
  }
  function chessSan(p, m) {
    const piece = Math.abs(p.b[m.from]);
    const after = chessApply(p, m);
    const check = chessInCheck(after, after.w);
    const mate = check && chessMoves(after).length === 0;
    const suffix = mate ? "#" : check ? "+" : "";
    if (piece === K && Math.abs(m.to - m.from) === 2) {
      return (m.to > m.from ? "O-O" : "O-O-O") + suffix;
    }
    const capture = !!p.b[m.to] || piece === P && m.to === p.ep;
    if (piece === P) {
      const body = capture ? String.fromCharCode(97 + FILE(m.from)) + "x" + chessSq(m.to) : chessSq(m.to);
      return body + (m.promo ? "=" + LETTER[m.promo] : "") + suffix;
    }
    const rivals = chessMoves(p).filter(
      (o) => o.to === m.to && o.from !== m.from && Math.abs(p.b[o.from]) === piece
    );
    let dis = "";
    if (rivals.length) {
      const sameFile = rivals.some((o) => FILE(o.from) === FILE(m.from));
      const sameRank = rivals.some((o) => RANK(o.from) === RANK(m.from));
      if (!sameFile) dis = String.fromCharCode(97 + FILE(m.from));
      else if (!sameRank) dis = String(RANK(m.from) + 1);
      else dis = chessSq(m.from);
    }
    return LETTER[piece] + dis + (capture ? "x" : "") + chessSq(m.to) + suffix;
  }
  function chessDeadMaterial(p) {
    const minor = [];
    for (let i = 0; i < 64; i++) {
      const t = Math.abs(p.b[i]);
      if (!t || t === K) continue;
      if (t === P || t === R || t === Q) return false;
      minor.push(p.b[i] > 0 ? i : -i - 1);
    }
    if (minor.length <= 1) return true;
    if (minor.length === 2) {
      const sq = minor.map((v) => v >= 0 ? v : -v - 1);
      const isB = (i) => Math.abs(p.b[i]) === B;
      if (isB(sq[0]) && isB(sq[1])) {
        const dark = (i) => FILE(i) + RANK(i) & 1;
        return dark(sq[0]) === dark(sq[1]);
      }
    }
    return false;
  }
  function chessEnd(p, reps) {
    if (chessMoves(p).length === 0) {
      if (chessInCheck(p, p.w)) return { over: true, winner: p.w ? "b" : "w", reason: "checkmate" };
      return { over: true, winner: null, reason: "stalemate" };
    }
    if (chessDeadMaterial(p)) return { over: true, winner: null, reason: "dead position" };
    if (p.half >= 100) return { over: true, winner: null, reason: "fifty-move rule" };
    const key = chessKey(p);
    let seen = 0;
    for (const r of reps) if (r === key) seen++;
    if (seen >= 3) return { over: true, winner: null, reason: "threefold repetition" };
    return { over: false };
  }
  function chessKey(p) {
    return chessFen(p).split(" ").slice(0, 4).join(" ");
  }
  return __toCommonJS(chess_src_exports);
})();

window.ChessRules = __CR;
